apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: orders
type: Opaque
stringData:
  POSTGRES_DB:       orders_db
  POSTGRES_USER:     ordersuser
  POSTGRES_PASSWORD: orderspass
